### ISSUE TITLE
Flag in readme? 

### ISSUE THREAD

**Issue by epierson9** [nuitrcs/examplejobs#1]
In https://raw.githubusercontent.com/nuitrcs/examplejobs/master/python/commandline_arguments/readme.md

should it be 

`msub -V ARG1=3,ARG2=hello myjob.sh`

with a capital V or 

`msub -v ARG1=3,ARG2=hello myjob.sh` 

with a lowercase v? Only the latter works for me.

**Comment by mrichnu** [comment]
Thanks, this is now fixed in the readme.
